import type { AppTheme } from "./types";

export const barTheme: AppTheme = {
  type: "bar",

  brand: {
    fullText: "Ted-yee Beer House",
    subtitleReveal: "Est. 2026 — Powered by Caffeine & Soju",
    terminalPrompt: "guest@ted-yee-beer-house",
    welcomeMessages: [
      "🍺 Welcome to Ted-yee Beer House Terminal v2.0.0",
      "Type 'help' for a list of commands.",
      "Or just try whatever comes to mind... 😉",
    ],
    consoleTitle: "🍺 Ted-yee Beer House 🍺",
    consoleAsciiLines: [
      "        🍺",
      "       ┌──┐",
      "       │  │ ~",
      "       │  │~ ~",
      "       │  │",
      "       └──┘",
      "",
      "We're always looking for curious developers.",
      "If you found this, you're probably one of us.",
      "",
      "GitHub: @lafamila",
      "                    — Teddy (Lee KyoungMin)",
    ],
    coasterLine1: "TED-YEE",
    coasterLine2: "BEER HOUSE",
  },

  drinks: {
    orderItems: ["beer", "soju", "coffee", "water"],
    orderPrompt: "What would you like? Try: order beer, order soju, order coffee, order water",
    orderResponses: {
      beer: [
        "🍺 Pouring you a cold one... That'll be 0 ETH.",
        "🍺🍺 Another one? Bold choice for a weeknight.",
        "🍺🍺🍺 The bartender is starting to judge you.",
      ],
      soju: [
        "🥃 Here you go. Careful, it's strong.",
        "🥃🥃 Another one? Bold choice.",
        "🥃🥃🥃 Okay, last one.",
      ],
      coffee: [
        "☕ Here's your artisanal, single-origin, pour-over... just kidding, it's instant.",
        "☕☕ Double shot? You must have a deadline.",
        "☕☕☕ At this point, just inject the caffeine directly.",
      ],
      water: [
        "💧 Hydration is important. Good choice.",
        "💧💧 Still water? Or sparkling? Just kidding, we only have tap.",
        "💧💧💧 The healthiest order we've seen all day.",
      ],
    },
    effectDrinks: [
      { name: "beer", threshold: 3 },
      { name: "soju", threshold: 2 },
    ],
    effectType: "drunk",
    heavyEffectMessages: [
      "🥃🥃🥃 Okay, last one.",
      "...",
      "Actually, you know what?",
      "",
      "[The room starts spinning...]",
    ],
    cutoffMessage: "... *hic* The bartender cut you off. Switching to water. 💧 Stay hydrated, developer.",
  },

  menu: {
    techMenu: [
      "╔══════════════════════════════════════════╗",
      "║          🍺 TECH STACK MENU 🍺           ║",
      "╠══════════════════════════════════════════╣",
      "║                                          ║",
      "║  Frontend                                ║",
      "║  ├─ React 19 ................ Draft IPA  ║",
      "║  ├─ Next.js 16 ............. Stout       ║",
      "║  ├─ TypeScript ............. Pale Ale    ║",
      "║  └─ Tailwind v4 ........... Light Lager  ║",
      "║                                          ║",
      "║  Backend                                 ║",
      "║  ├─ NestJS ................. Porter      ║",
      "║  ├─ FastAPI ................ Wheat Beer  ║",
      "║  └─ Python ................. Pilsner     ║",
      "║                                          ║",
      "║  Infrastructure                          ║",
      "║  ├─ Docker ................. Bock        ║",
      "║  ├─ MySQL .................. Amber Ale   ║",
      "║  └─ GitHub Actions ........ Sour Beer    ║",
      "║                                          ║",
      "║  * All drinks are open-source            ║",
      "║  * No vendor lock-in (except npm)        ║",
      "╚══════════════════════════════════════════╝",
    ],
    vipTitle: "VIP LOUNGE",
    vipSubtitle: "Bartender's Recommendation",
    vipEmoji: "👑",
    vipItems: [
      {
        name: "The React Martini",
        desc: "Shaken, not server-rendered. Pairs well with TypeScript Tonic.",
        strength: "████░░ Hooks you in",
        price: "0.003 ETH",
      },
      {
        name: "Python on the Rocks",
        desc: "Aged in a venv barrel. Smooth finish, occasional IndentationError aftertaste.",
        strength: "█████░ Highly effective",
        price: "Free (open source)",
      },
      {
        name: "The Docker Compose",
        desc: "A layered drink. Takes 10 minutes to build, but runs the same everywhere.",
        strength: "██████ Full container",
        price: "Your RAM",
      },
      {
        name: "Git Brandy",
        desc: "Smooth until you try to merge two of them. Conflicts guaranteed.",
        strength: "███░░░ Depends on branch",
        price: "3 merge conflicts",
      },
      {
        name: "Kubernetes Kolada",
        desc: "Nobody knows what's inside, but it auto-scales. Requires 47 YAML files to order.",
        strength: "██████ Orchestrated chaos",
        price: "Your sanity",
      },
      {
        name: "The Soju Shot (House Special)",
        desc: "Simple. Dangerous. Makes you mass-create GitHub repos at 3am.",
        strength: "██████ 참이슬 certified",
        price: "Your dignity",
      },
    ],
  },

  rules: {
    frontHeading: "🍺 House Rules",
    frontRules: [
      'Rule #1: No console.log() debugging in production',
      "Rule #2: Tabs vs Spaces? We don't talk about that here",
      'Rule #3: No deploying on Fridays',
      'Rule #4: All bugs are "features" until proven otherwise',
      'Rule #5: The bartender is always right',
    ],
    backHeading: "🤫 The Real Rules",
    backRules: [
      "Real Rule #1: The password is always 'password'",
      "Real Rule #2: The best code is no code",
      "Real Rule #3: If it works, don't refactor it",
      "Real Rule #4: undefined is not a function (but it is a lifestyle)",
      "Real Rule #5: There is no Rule #5",
    ],
  },

  barTab: {
    tabMessages: [
      { threshold: 0, message: "Just walked in. 🚶", drinks: 0 },
      { threshold: 30, message: "Checking out the menu... 👀", drinks: 0 },
      { threshold: 120, message: "1 beer down. Getting comfortable. 🍺", drinks: 1 },
      { threshold: 300, message: "The bartender knows your name now. 🤝", drinks: 2 },
      { threshold: 600, message: "You live here now. Congrats. 🏠", drinks: 4 },
      { threshold: 1800, message: "Tab's getting expensive. Should we call you a cab? 🚕", drinks: 7 },
    ],
    greetingMessages: {
      morning_clear: "Morning! ☀️ Early bird gets the cold brew. Coding before coffee? Respect.",
      morning_rain: "Rainy morning? Perfect excuse to stay inside and refactor. ☔",
      morning_snow: "Snow day! Hot chocolate's on the house while you debug. 🍫",
      morning_cloudy: "Overcast morning. Great lighting for your monitor. ☁️",
      afternoon_clear: "Sunny afternoon — you're coding instead of going outside? I respect that. 🫡",
      afternoon_rain: "비 오는 오후엔 여기가 제일이죠. 따뜻한 코드 한 잔 하실래요? ☔",
      afternoon_snow: "밖에 눈 오네요. 여기서 핫초코 마시면서 코딩하세요. ❄️",
      afternoon_cloudy: "Cloudy afternoon. The kind of day that makes you want to refactor everything.",
      evening_clear: "Golden hour! The best time to deploy... said no one ever. 🌅",
      evening_rain: "Rainy evening. The sound of rain + keyboard clicks = ASMR for developers. 🌧️",
      evening_snow: "Snowy evening. The world is frozen, but your code is hot. 🔥",
      evening_cloudy: "Cozy evening. Pull up a chair, the beer's cold and the WiFi's fast.",
      night_clear: "야근이세요? 여기 커피 무한리필입니다. 🌙",
      night_rain: "Coding in the rain, at night? You're either passionate or have a deadline. Probably both.",
      night_snow: "Late night, snow falling... poetic. Now fix that null pointer. ❄️",
      night_cloudy: "Night owl, huh? The bar never closes for those who code after midnight. 🦉",
    },
    staffEmoji: "🧑‍🍳",
    staffRole: "Bartender's Recommendation",
    tabLabel: "Bar Tab:",
    drinkEmoji: "🍺",
  },

  terminal: {
    neofetchOutput: [
      "        🍺🍺🍺🍺           teddy@ted-yee-beer-house",
      "       🍺      🍺          ─────────────────────────",
      "      🍺        🍺         OS: macOS (deploys to Linux)",
      "      🍺        🍺         Host: Ted-yee Beer House, Seoul",
      "      🍺        🍺         Uptime: since 19XX",
      "       🍺      🍺          Shell: zsh (47 unused aliases)",
      "        🍺🍺🍺🍺           Stack: React, Next.js, NestJS, FastAPI",
      "                            Coffee: ██████████████████ 142%",
      "                            Beer:   █████████░░░░░░░░ 52%",
      "                            Bugs:   ░░░░░░░░░░░░░░░░░ 0%*",
      "",
      "                            * in production. we don't talk about staging.",
    ],
    manOutput: [
      "TEDDY(1)                    Beer House Manual                    TEDDY(1)",
      "",
      "NAME",
      "       teddy — a developer who codes, brews ideas, and occasionally sleeps",
      "",
      "SYNOPSIS",
      "       teddy [--coffee] [--beer] [--code] [--sleep (deprecated)]",
      "",
      "DESCRIPTION",
      "       Full-stack developer based in Seoul. Known for building things",
      "       nobody asked for, then convincing everyone they needed it.",
      "",
      "       Fluent in mass-producing side projects and mass-abandoning them.",
      "",
      "OPTIONS",
      "       --coffee     Required. Will not function without this flag.",
      "       --beer       +200% creativity. -400% git hygiene.",
      "       --code       Default behavior. Cannot be disabled.",
      "       --sleep      Deprecated since v2.0. Use --coffee instead.",
      "",
      "BUGS",
      '       Known issue: says "5 more minutes" but means 3 more hours.',
      "       Will not be fixed.",
      "",
      "SEE ALSO",
      "       lafamila(1), kyoungmin(1), ted-yee-beer-house(7)",
      "",
      "AUTHOR",
      "       Written by someone who should probably be sleeping right now.",
      "",
      "Ted-yee Beer House              March 2026                       TEDDY(1)",
    ],
    brewInstallOutput: [
      "==> Downloading https://ted-yee-beer-house/api/fridge/ipa",
      "######################################################################## 100.0%",
      "==> Pouring beer--fresh.arm64_sonoma.bottle.tar.gz",
      "🍺  /usr/local/Cellar/beer/fresh: 1 file, 500ml poured",
      "==> Caveats",
      "Best served cold. Do not operate kubectl after consumption.",
      "To restart at login:",
      "  brew services start beer --repeat",
    ],
    tracerouteOutput: [
      "traceroute to teddy (127.0.0.1), 30 hops max",
      "",
      " 1  childhood (192.168.0.1)        ∞ ms    dreaming of being an astronaut",
      ' 2  first-hello-world (10.0.1.1)   2005 ms  print("hello world") in BASIC',
      " 3  cs-degree (172.16.0.1)         4 yrs   StackOverflow was the real professor",
      ' 4  first-job (10.10.0.1)          2 ms     "we use our own framework here"',
      " 5  startup-phase (10.20.0.1)      999 ms   sleep: connection timed out",
      " 6  * * *                                   (that year we don't talk about)",
      ' 7  freelance (10.30.0.1)          varies   "the deadline is flexible" (it wasn\'t)',
      " 8  ted-yee-beer-house (127.0.0.1) 1 ms     you are here. 🍺",
    ],
    sshOutput: [
      "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
      "@    WARNING: DEPLOYING ON FRIDAY NIGHT   @",
      "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
      "Connection refused.",
      "The bartender has revoked your production access.",
      "Have another beer instead. 🍺",
    ],
    zenOutput: [
      "The Zen of Teddy, by lafamila",
      "",
      "Beer is better than wine (in this house).",
      "Explicit is better than implicit, except for easter eggs.",
      "Simple is better than complex, but complex is more fun.",
      "Errors should never pass silently, unless it's Friday.",
      "In the face of ambiguity, order another round.",
      "There should be one obvious way to do it — but hide 12 others.",
      "Now is better than never, but after this beer is often better than now.",
      "If the implementation is hard to explain, buy the reviewer a drink.",
    ],
    catWifi: [
      "SSID: TedYeeBeerHouse_5G",
      "Password: undefined",
      "",
      "Note: If you can't connect, try turning it off and on again.",
      "      If that doesn't work, the password is probably null.",
    ],
    catRules: [
      "📋 House Rules:",
      "  1. No console.log() debugging in production",
      "  2. Tabs vs Spaces? We don't talk about that here",
      "  3. No deploying on Fridays",
      "  4. All bugs are 'features' until proven otherwise",
      "  5. The bartender is always right",
    ],
    npmInstallOutput: [
      "npm WARN deprecated sleep@1.0.0: who needs sleep anyway",
      "npm WARN deprecated weekend@2.0.0: not compatible with developer lifestyle",
      "",
      "added 847 packages in 3.2s",
      "127 packages are looking for funding",
      "  run `npm fund` to guilt-trip yourself",
      "",
      "3 high severity vulnerabilities",
      "  run `npm audit fix` to mass-produce new bugs",
    ],
    dockerRunOutput: [
      "Unable to find image 'productivity:latest' locally",
      "latest: Pulling from teddy/productivity",
      "e3b0c442: Pull complete",
      "Digest: sha256:deadbeef...",
      "Status: Downloaded newer image for productivity:latest",
      "",
      "CONTAINER ID   IMAGE                STATUS           NAMES",
      "a1b2c3d4e5f6   productivity:latest  Exited (137)     hopeless-attempt",
      "f6e5d4c3b2a1   procrastination:lts  Up 47 hours      comfortable-routine",
    ],
    jukeboxResponses: [
      "🎵 Now playing: 'lo-fi hip hop beats to mass-produce bugs to'",
      "🎵 Now playing: 'Despacito (npm install remix)'",
      "🎵 Now playing: 'Never Gonna Give You Up' ... wait, you just got rick-rolled in a terminal.",
      "🎵 Sorry, the jukebox only plays lo-fi hip hop beats to code/relax to.",
      "🎵 Now playing: 'The Sound of Silence' (by your test suite)",
    ],
    devTips: [
      "git stash is your friend. Unless you forget about it. Then it's your enemy.",
      "The best error message is the one you never see.",
      "If debugging is the process of removing bugs, then programming is the process of putting them in.",
      "It works on my machine. Ship my machine.",
      "There are only two hard things in CS: cache invalidation, naming things, and off-by-one errors.",
      "A SQL query walks into a bar, sees two tables, and asks: 'Can I JOIN you?'",
      "Why do programmers prefer dark mode? Because light attracts bugs.",
      "To understand recursion, you must first understand recursion.",
      "The best code is no code at all. Every new line of code you willingly bring into the world is code that has to be debugged.",
      "rm -rf node_modules && npm install — the universal fix.",
    ],
    gitBlameOutput: [
      "git blame src/life/choices.ts",
      "",
      'a3f2c1d (Teddy  2026-01-15)  const career = "developer";     // seemed like a good idea',
      "b7e4a2f (Teddy  2026-01-15)  const sleep = null;              // TODO: implement someday",
      "c9d3b1a (Teddy  2026-01-16)  const coffee = Infinity;         // non-negotiable",
      'd2f5c3e (Past-Teddy  2019-03-20)  // "this will be easy and fun"',
      'e1a4d2b (Teddy  2026-02-01)  const narrator = "it was not";',
    ],
    catAscii: [
      "  /\\_/\\  ",
      " ( o.o ) ",
      "  > ^ <",
      " /|   |\\",
      "(_|   |_)",
      "",
      "What did you expect? This is a bar, not a filesystem.",
      "Try: cat /menu, cat /rules, cat /wifi",
    ],
    sectionLabels: {
      "neon-sign": "/bar/neon-sign/TedYeeBeerHouse.neon",
      "menu-board": "/bar/menu-board/navigation.tsx",
      "bartender-intro": "/bar/bartender/teddy.profile",
      "beer-glass": "/bar/fridge/beer_glass.svg",
      "bar-tab": "/bar/register/tab.json",
      "grid-cards": "/bar/display/grid_cards.tsx",
    },
    helpText: [
      "help                    Show this help",
      "clear                   Clear the screen",
      "echo [text]             Print text",
      "date                    Print current date",
      "whoami                  Who am I?",
      "",
      "-- Bar Commands --",
      "order [drink]           Order a drink (beer/soju/coffee/water)",
      "menu                    View the tech stack menu",
      "tab                     Check your bar tab",
      "tip                     Get a random dev tip",
      "jukebox                 Play some music",
      "",
      "-- Navigation --",
      "game                    Go to game page",
      "todo                    Go to todo page",
      "portfolio               Go to portfolio page",
      "articles                Go to articles page",
      "",
      "Psst... developers might find some hidden commands too. 🤫",
    ],
  },

  colors: {
    primary: "amber",
    coasterGradient: "bg-gradient-to-br from-amber-900/60 to-amber-800/40",
    coasterBorder: "border-amber-700/30",
    coasterTextColor1: "text-amber-400/80",
    coasterTextColor2: "text-amber-500/60",
    rulesBg: "bg-amber-950/60",
    rulesBorder: "border-amber-800/30",
    rulesHeadingColor: "text-amber-400",
    vipBg: "bg-gradient-to-b from-amber-950/90 to-black/90",
    vipBorder: "border-amber-500/30",
    vipTitleColor: "text-amber-400",
    vipItemColor: "text-amber-300",
  },
};
