import type { AppTheme } from "./types";

export const cafeTheme: AppTheme = {
  type: "cafe",

  brand: {
    fullText: "Ted-yee Coffee House",
    subtitleReveal: "Est. 2026 — Powered by Espresso & Ambition",
    terminalPrompt: "guest@ted-yee-coffee-house",
    welcomeMessages: [
      "☕ Welcome to Ted-yee Coffee House Terminal v2.0.0",
      "Type 'help' for a list of commands.",
      "Or just try whatever comes to mind... 😉",
    ],
    consoleTitle: "☕ Ted-yee Coffee House ☕",
    consoleAsciiLines: [
      "        ☕",
      "       ┌──┐",
      "       │  │ ~",
      "       │  │~ ~",
      "       │  │",
      "       └──┘",
      "",
      "We're always looking for curious developers.",
      "If you found this, you're probably one of us.",
      "",
      "GitHub: @lafamila",
      "                    — Teddy (Lee KyoungMin)",
    ],
    coasterLine1: "TED-YEE",
    coasterLine2: "COFFEE HOUSE",
  },

  drinks: {
    orderItems: ["latte", "espresso", "tea", "water"],
    orderPrompt: "What would you like? Try: order latte, order espresso, order tea, order water",
    orderResponses: {
      latte: [
        "☕ One latte, coming right up... with a little heart drawn on top.",
        "☕☕ Another latte? The barista is showing off their latte art now.",
        "☕☕☕ You're basically on an IV drip of milk and espresso.",
      ],
      espresso: [
        "☕ One shot of espresso. Pure, concentrated focus.",
        "☕☕ Double shot? Your keyboard is about to feel your wrath.",
        "☕☕☕ Triple shot. Your heart rate is now a TODO item.",
      ],
      tea: [
        "🍵 A cup of tea. Calm, collected, very unlike your git history.",
        "🍵🍵 Another cup? You're the most peaceful developer here.",
        "🍵🍵🍵 Are you sure you're a developer? This much zen is suspicious.",
      ],
      water: [
        "💧 Hydration is important. Good choice.",
        "💧💧 Still water? Or sparkling? Just kidding, we only have tap.",
        "💧💧💧 The healthiest order we've seen all day.",
      ],
    },
    effectDrinks: [
      { name: "espresso", threshold: 2 },
      { name: "latte", threshold: 3 },
    ],
    effectType: "caffeinated",
    heavyEffectMessages: [
      "☕☕☕ That's a lot of caffeine.",
      "...",
      "You can feel it kicking in...",
      "",
      "[Your hands start trembling...]",
    ],
    cutoffMessage: "... *jitter* The barista cut you off. Switching to decaf. 🫖 Your heart will thank you.",
  },

  menu: {
    techMenu: [
      "╔══════════════════════════════════════════╗",
      "║        ☕ TECH STACK MENU ☕              ║",
      "╠══════════════════════════════════════════╣",
      "║                                          ║",
      "║  Frontend                                ║",
      "║  ├─ React 19 ................ Espresso   ║",
      "║  ├─ Next.js 16 ............. Cold Brew   ║",
      "║  ├─ TypeScript ............. Americano   ║",
      "║  └─ Tailwind v4 ........... Flat White   ║",
      "║                                          ║",
      "║  Backend                                 ║",
      "║  ├─ NestJS ................. Cappuccino  ║",
      "║  ├─ FastAPI ................ Pour Over   ║",
      "║  └─ Python ................. Drip        ║",
      "║                                          ║",
      "║  Infrastructure                          ║",
      "║  ├─ Docker ................. Matcha      ║",
      "║  ├─ MySQL .................. Chai Latte  ║",
      "║  └─ GitHub Actions ........ Decaf       ║",
      "║                                          ║",
      "║  * All drinks are fair-trade              ║",
      "║  * No vendor lock-in (except caffeine)   ║",
      "╚══════════════════════════════════════════╝",
    ],
    vipTitle: "MEMBER'S LOUNGE",
    vipSubtitle: "Barista's Selection",
    vipEmoji: "✨",
    vipItems: [
      {
        name: "The React Affogato",
        desc: "Espresso poured over vanilla ice cream. Like hot reloading, but delicious.",
        strength: "████░░ Hooks you in",
        price: "0.003 ETH",
      },
      {
        name: "Python Pour Over",
        desc: "Slow-brewed in a venv filter. Clean finish, occasional IndentationError aftertaste.",
        strength: "█████░ Highly effective",
        price: "Free (open source)",
      },
      {
        name: "The Docker Frappuccino",
        desc: "A layered drink. Takes 10 minutes to build, but tastes the same everywhere.",
        strength: "██████ Full container",
        price: "Your RAM",
      },
      {
        name: "Git Blend",
        desc: "Smooth until you try to merge two of them. Flavor conflicts guaranteed.",
        strength: "███░░░ Depends on beans",
        price: "3 merge conflicts",
      },
      {
        name: "Kubernetes Kombucha",
        desc: "Nobody knows what's fermenting inside, but it auto-scales. Requires 47 YAML files to order.",
        strength: "██████ Orchestrated chaos",
        price: "Your sanity",
      },
      {
        name: "The Espresso Shot (House Special)",
        desc: "Simple. Intense. Makes you mass-refactor codebases at 3am.",
        strength: "██████ Barista certified",
        price: "Your sleep schedule",
      },
    ],
  },

  rules: {
    frontHeading: "☕ House Rules",
    frontRules: [
      'Rule #1: No console.log() debugging in production',
      "Rule #2: Tabs vs Spaces? We don't discuss that over coffee",
      'Rule #3: No deploying on Fridays',
      'Rule #4: All bugs are "features" until proven otherwise',
      'Rule #5: The barista is always right',
    ],
    backHeading: "🤫 The Real Rules",
    backRules: [
      "Real Rule #1: The wifi password is always 'password'",
      "Real Rule #2: The best code is no code",
      "Real Rule #3: If it works, don't refactor it (order another latte instead)",
      "Real Rule #4: undefined is not a function (but it is a lifestyle)",
      "Real Rule #5: There is no Rule #5 (like decaf espresso, it shouldn't exist)",
    ],
  },

  barTab: {
    tabMessages: [
      { threshold: 0, message: "Just walked in. 🚶", drinks: 0 },
      { threshold: 30, message: "Eyeing the pastry display... 👀", drinks: 0 },
      { threshold: 120, message: "1 latte down. Setting up the laptop. ☕", drinks: 1 },
      { threshold: 300, message: "The barista knows your order now. 🤝", drinks: 2 },
      { threshold: 600, message: "You've claimed this table. It's yours now. 🏠", drinks: 4 },
      { threshold: 1800, message: "You've been here all day. Should we charge rent? 🏢", drinks: 7 },
    ],
    greetingMessages: {
      morning_clear: "Morning! ☀️ Early bird gets the fresh pour-over. The beans are just roasted.",
      morning_rain: "Rainy morning? Nothing pairs better with code than a warm cup. ☔",
      morning_snow: "Snow day! Hot chocolate's on the house while you debug. 🍫",
      morning_cloudy: "Overcast morning. Perfect vibes for a cozy café session. ☁️",
      afternoon_clear: "Sunny afternoon — you're coding instead of going outside? Here's an iced latte. 🫡",
      afternoon_rain: "비 오는 오후엔 여기가 제일이죠. 따뜻한 라떼 한 잔 하실래요? ☔",
      afternoon_snow: "밖에 눈 오네요. 여기서 핫초코 마시면서 코딩하세요. ❄️",
      afternoon_cloudy: "Cloudy afternoon. The kind of day that calls for an extra shot of espresso.",
      evening_clear: "Golden hour! The best time to deploy... said no one ever. Here, have a decaf. 🌅",
      evening_rain: "Rainy evening. The sound of rain + coffee + keyboard = peak productivity. 🌧️",
      evening_snow: "Snowy evening. The world is frozen, but your code is hot. 🔥",
      evening_cloudy: "Cozy evening. Pull up a chair, the espresso's fresh and the WiFi's fast.",
      night_clear: "야근이세요? 여기 커피 무한리필입니다. 🌙",
      night_rain: "Late night coffee run in the rain? You're either passionate or have a deadline.",
      night_snow: "Late night, snow falling... poetic. Maybe switch to decaf? ❄️",
      night_cloudy: "Night owl, huh? The café never closes for those who code after midnight. 🦉",
    },
    staffEmoji: "☕",
    staffRole: "Barista's Selection",
    tabLabel: "Café Tab:",
    drinkEmoji: "☕",
  },

  terminal: {
    neofetchOutput: [
      "        ☕☕☕☕           teddy@ted-yee-coffee-house",
      "       ☕      ☕          ─────────────────────────",
      "      ☕        ☕         OS: macOS (deploys to Linux)",
      "      ☕        ☕         Host: Ted-yee Coffee House, Seoul",
      "      ☕        ☕         Uptime: since 19XX",
      "       ☕      ☕          Shell: zsh (47 unused aliases)",
      "        ☕☕☕☕           Stack: React, Next.js, NestJS, FastAPI",
      "                            Coffee: ██████████████████ 142%",
      "                            Focus:  █████████████░░░░ 78%",
      "                            Bugs:   ░░░░░░░░░░░░░░░░░ 0%*",
      "",
      "                            * in production. we don't talk about staging.",
    ],
    manOutput: [
      "TEDDY(1)                   Coffee House Manual                   TEDDY(1)",
      "",
      "NAME",
      "       teddy — a developer who codes, brews ideas, and occasionally sleeps",
      "",
      "SYNOPSIS",
      "       teddy [--espresso] [--latte] [--code] [--sleep (deprecated)]",
      "",
      "DESCRIPTION",
      "       Full-stack developer based in Seoul. Known for building things",
      "       nobody asked for, then convincing everyone they needed it.",
      "",
      "       Fluent in mass-producing side projects and mass-abandoning them.",
      "",
      "OPTIONS",
      "       --espresso   Required. Will not function without this flag.",
      "       --latte      +200% comfort. -400% productivity.",
      "       --code       Default behavior. Cannot be disabled.",
      "       --sleep      Deprecated since v2.0. Use --espresso instead.",
      "",
      "BUGS",
      '       Known issue: says "5 more minutes" but means 3 more hours.',
      "       Will not be fixed.",
      "",
      "SEE ALSO",
      "       lafamila(1), kyoungmin(1), ted-yee-coffee-house(7)",
      "",
      "AUTHOR",
      "       Written by someone who should probably be sleeping right now.",
      "",
      "Ted-yee Coffee House            March 2026                       TEDDY(1)",
    ],
    brewInstallOutput: [
      "==> Downloading https://ted-yee-coffee-house/api/bar/espresso",
      "######################################################################## 100.0%",
      "==> Brewing espresso--fresh.arm64_sonoma.bottle.tar.gz",
      "☕  /usr/local/Cellar/coffee/fresh: 1 file, 60ml brewed",
      "==> Caveats",
      "Best served hot. Do not operate kubectl after 3rd shot.",
      "To restart at login:",
      "  brew services start coffee --repeat",
    ],
    tracerouteOutput: [
      "traceroute to teddy (127.0.0.1), 30 hops max",
      "",
      " 1  childhood (192.168.0.1)        ∞ ms    dreaming of being an astronaut",
      ' 2  first-hello-world (10.0.1.1)   2005 ms  print("hello world") in BASIC',
      " 3  cs-degree (172.16.0.1)         4 yrs   StackOverflow was the real professor",
      ' 4  first-job (10.10.0.1)          2 ms     "we use our own framework here"',
      " 5  startup-phase (10.20.0.1)      999 ms   sleep: connection timed out",
      " 6  * * *                                   (that year we don't talk about)",
      ' 7  freelance (10.30.0.1)          varies   "the deadline is flexible" (it wasn\'t)',
      " 8  ted-yee-coffee-house (127.0.0.1) 1 ms   you are here. ☕",
    ],
    sshOutput: [
      "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
      "@    WARNING: DEPLOYING ON FRIDAY NIGHT   @",
      "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
      "Connection refused.",
      "The barista has revoked your production access.",
      "Have another espresso instead. ☕",
    ],
    zenOutput: [
      "The Zen of Teddy, by lafamila",
      "",
      "Coffee is better than energy drinks (in this house).",
      "Explicit is better than implicit, except for easter eggs.",
      "Simple is better than complex, but complex is more fun.",
      "Errors should never pass silently, unless it's Friday.",
      "In the face of ambiguity, order another espresso.",
      "There should be one obvious way to do it — but hide 12 others.",
      "Now is better than never, but after this coffee is often better than now.",
      "If the implementation is hard to explain, buy the reviewer a latte.",
    ],
    catWifi: [
      "SSID: TedYeeCoffeeHouse_5G",
      "Password: undefined",
      "",
      "Note: If you can't connect, try turning it off and on again.",
      "      If that doesn't work, the password is probably null.",
    ],
    catRules: [
      "📋 House Rules:",
      "  1. No console.log() debugging in production",
      "  2. Tabs vs Spaces? We don't discuss that over coffee",
      "  3. No deploying on Fridays",
      "  4. All bugs are 'features' until proven otherwise",
      "  5. The barista is always right",
    ],
    npmInstallOutput: [
      "npm WARN deprecated sleep@1.0.0: who needs sleep anyway",
      "npm WARN deprecated weekend@2.0.0: not compatible with developer lifestyle",
      "",
      "added 847 packages in 3.2s",
      "127 packages are looking for funding",
      "  run `npm fund` to guilt-trip yourself",
      "",
      "3 high severity vulnerabilities",
      "  run `npm audit fix` to mass-produce new bugs",
    ],
    dockerRunOutput: [
      "Unable to find image 'productivity:latest' locally",
      "latest: Pulling from teddy/productivity",
      "e3b0c442: Pull complete",
      "Digest: sha256:deadbeef...",
      "Status: Downloaded newer image for productivity:latest",
      "",
      "CONTAINER ID   IMAGE                STATUS           NAMES",
      "a1b2c3d4e5f6   productivity:latest  Exited (137)     hopeless-attempt",
      "f6e5d4c3b2a1   procrastination:lts  Up 47 hours      comfortable-routine",
    ],
    jukeboxResponses: [
      "🎵 Now playing: 'lo-fi hip hop beats to mass-produce bugs to'",
      "🎵 Now playing: 'Bossa Nova Debugging Session'",
      "🎵 Now playing: 'Never Gonna Give You Up' ... wait, you just got rick-rolled in a terminal.",
      "🎵 Sorry, the café only plays lo-fi and jazz to code/relax to.",
      "🎵 Now playing: 'The Sound of Silence' (by your test suite)",
    ],
    devTips: [
      "git stash is your friend. Unless you forget about it. Then it's your enemy.",
      "The best error message is the one you never see.",
      "If debugging is the process of removing bugs, then programming is the process of putting them in.",
      "It works on my machine. Ship my machine.",
      "There are only two hard things in CS: cache invalidation, naming things, and off-by-one errors.",
      "A SQL query walks into a café, sees two tables, and asks: 'Can I JOIN you?'",
      "Why do programmers prefer dark mode? Because light attracts bugs.",
      "To understand recursion, you must first understand recursion.",
      "The best code is no code at all. Every new line of code you willingly bring into the world is code that has to be debugged.",
      "rm -rf node_modules && npm install — the universal fix.",
    ],
    gitBlameOutput: [
      "git blame src/life/choices.ts",
      "",
      'a3f2c1d (Teddy  2026-01-15)  const career = "developer";     // seemed like a good idea',
      "b7e4a2f (Teddy  2026-01-15)  const sleep = null;              // TODO: implement someday",
      "c9d3b1a (Teddy  2026-01-16)  const coffee = Infinity;         // non-negotiable",
      'd2f5c3e (Past-Teddy  2019-03-20)  // "this will be easy and fun"',
      'e1a4d2b (Teddy  2026-02-01)  const narrator = "it was not";',
    ],
    catAscii: [
      "  /\\_/\\  ",
      " ( o.o ) ",
      "  > ^ <",
      " /|   |\\",
      "(_|   |_)",
      "",
      "What did you expect? This is a café, not a filesystem.",
      "Try: cat /menu, cat /rules, cat /wifi",
    ],
    sectionLabels: {
      "neon-sign": "/cafe/neon-sign/TedYeeCoffeeHouse.neon",
      "menu-board": "/cafe/menu-board/navigation.tsx",
      "bartender-intro": "/cafe/barista/teddy.profile",
      "beer-glass": "/cafe/counter/coffee_cup.svg",
      "bar-tab": "/cafe/register/tab.json",
      "grid-cards": "/cafe/display/grid_cards.tsx",
    },
    helpText: [
      "help                    Show this help",
      "clear                   Clear the screen",
      "echo [text]             Print text",
      "date                    Print current date",
      "whoami                  Who am I?",
      "",
      "-- Café Commands --",
      "order [drink]           Order a drink (latte/espresso/tea/water)",
      "menu                    View the tech stack menu",
      "tab                     Check your café tab",
      "tip                     Get a random dev tip",
      "jukebox                 Play some music",
      "",
      "-- Navigation --",
      "game                    Go to game page",
      "todo                    Go to todo page",
      "portfolio               Go to portfolio page",
      "articles                Go to articles page",
      "",
      "Psst... developers might find some hidden commands too. 🤫",
    ],
  },

  colors: {
    primary: "brown",
    coasterGradient: "bg-gradient-to-br from-stone-800/60 to-stone-700/40",
    coasterBorder: "border-stone-600/30",
    coasterTextColor1: "text-stone-300/80",
    coasterTextColor2: "text-stone-400/60",
    rulesBg: "bg-stone-900/60",
    rulesBorder: "border-stone-700/30",
    rulesHeadingColor: "text-stone-300",
    vipBg: "bg-gradient-to-b from-stone-900/90 to-black/90",
    vipBorder: "border-stone-500/30",
    vipTitleColor: "text-stone-300",
    vipItemColor: "text-stone-200",
  },
};
